[package]
name = "akari-verify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akari = {path = "../../lib/akari"}
clap = "2.33.3"

[[bin]]
name="akr-verify"
path="src/main.rs"